import { objectType } from 'Nexus'
import { User } from './User'

export const Order = objectType({
    definition(t) {
        t.string('id');
        t.string('orderId')
        t.string('createdAt')
        t.string('updatedAt')
        t.boolean('pending')
        t.boolean('accepted')
        t.string('acceptedBy')
        t.string('acceptedAt')
        t.boolean('sold')
        t.string('soldBy')
        t.string('soldAt')
        t.boolean('canceled')
        t.string('canceledBy')
        t.string('canceledAt')
        t.string('canceledWhy')
        t.string('userEmail')
        t.string('emailVerified')
        t.string('firstName')
        t.string('lastName')
        t.string('phoneNumber')
        t.string('countryName')
        t.string('city')
        t.string('user_commune')
        t.string('vendeurs')
        t.string('villes1')
        t.string('adresses')
        t.string('telephone1')
        t.string('telephone2')
        t.string('fix1')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
        t.int('')
        t.string('')
        t.string('')
        t.string('')
        t.string('')
    }
})

t.boolean('')
t.string('')