
const   vendeurs
const    product_names
const    product_imagelinks
const    marques
const    categories
const    product_links
const    product_prices
const    vendeurs_image 
const    villes1 
const    adresses 
const    telephone1 
const     telephone2 
const    fix1 
const   email 
const   facebook 
const    instagram 
const   horaires 
const   localisation 
const   stocks 
const    shop_website 
const   product_country 
const   commune 
const  livraison 
const   paiement 
const   type 