
const vendeurs = hit.fields.
const product_names= hit.fields.
const product_imagelinks= hit.fields.
const marques= hit.fields.
const categories= hit.fields.
const product_links= hit.fields.
const product_prices= hit.fields.
const vendeurs_image = hit.fields.
const villes1 =
const adresses =
const telephone1 =
const telephone2 =
const fix1 =
const email =
const facebook =
const instagram =
const horaires =
const localisation =
const stocks =
const shop_website =
const product_country =
const commune =
const livraison =
const paiement =
const type =