
const vendeurs = hit.fields.
const product_names= hit.fields.
const product_imagelinks= hit.fields.
const marques= hit.fields.
const categories= hit.fields.
const product_links= hit.fields.
const product_prices= hit.fields.
const vendeurs_image = hit.fields.
const villes1 = hit.fields.
const adresses = hit.fields.
const telephone1 = hit.fields.
const telephone2 = hit.fields.
const fix1 = hit.fields.
const email = hit.fields.
const facebook = hit.fields.
const instagram = hit.fields.
const horaires = hit.fields.
const localisation =
const stocks =
const shop_website =
const product_country =
const commune =
const livraison =
const paiement =
const type =